### ISSUE TITLE
Status of this repository

### ISSUE THREAD

**Issue by nomeata** [strake/frown#1]
Hi,

what is the status of this repository? Is this a maintained forked of frown? Do you plan to upload it to hackage? Add it to stackage?

Thanks,
Joachim

**Comment by strake** [comment]
> Is this a maintained forked of frown?

Not quite maintained now, but i'm willing to do it. I'll need to hack it some to build it with Cabal, but when i do i'll upload it to Hackage. When that's done i'll think about adding it to Stackage; i might want a co-maintainer if i do, not sure yet.

**Comment by strake** [comment]
Now on Hackage: https://hackage.haskell.org/package/frown

**Comment by nomeata** [comment]
Thanks. A few nitpicks.

Can you bump the version to something > 0.6.1? That is the version shipped in Debian at the moment.

It also seems that the tarball you uploaded misses a lot of modules, if you compare it to
https://sources.debian.net/src/frown/0.6.1-14/, and indeed, I cannot build it using cabal.

Documentation and examples are also lost in the process.

A package description is missing. You can have a look at https://packages.debian.org/unstable/frown for inspiration.

**Comment by strake** [comment]
Whoops, i forgot to tell cabal which files to include, and it never warned me. Try the latest ☺

**Comment by nomeata** [comment]
Ok, better.

I have problems building the documentation, though:

```
$ rm -rf Manual/html/ && make -C Manual html
make: Verzeichnis „/home/jojo/debian/pkg-haskell/packages/p/frown/Manual“ wird betreten
lhs2TeX --math Manual.lhs > Manual.tex
lhs2TeX: ./Manual.lhs: hGetContents: invalid argument (invalid byte sequence)
Makefile:107: die Regel für Ziel „html“ scheiterte
make: *** [html] Fehler 1
make: Verzeichnis „/home/jojo/debian/pkg-haskell/packages/p/frown/Manual“ wird verlassen
```

The problems seems to be a mis-encoding `Manual.lhs`:

```
$ file --mime-encoding Manual/./Manual.lhs
Manual/./Manual.lhs: unknown-8bit
```

I suggest to change them all to plain utf8 (or simply remove the outdated contact information).

If I do that locally, the next problem is another missing file:

```
~/debian/pkg-haskell/packages/p/frown $ make -C Manual html
make: Verzeichnis „/home/jojo/debian/pkg-haskell/packages/p/frown/Manual“ wird betreten
lhs2TeX --math Manual.lhs > Manual.tex
lhs2TeX: user error (File `../QuickStart/Tiger.lg' not found or not readable in search path:
   .
   /home/jojo/lhs2tex-1.19
   /home/jojo/lhs2tex
   /home/jojo/lhs2TeX
   /home/jojo/.lhs2tex-1.19
   /home/jojo/.lhs2tex
   /home/jojo/.lhs2TeX
   /usr/share/lhs2tex-1.19
   /usr/local/share/lhs2tex-1.19
   /usr/local/lib/lhs2tex-1.19
   /usr/lib/lhs2tex-1.19
   /usr/local/share/lhs2tex
   /usr/local/lib/lhs2tex
   /usr/share/lhs2tex
   /usr/lib/lhs2tex
   /usr/local/share/lhs2TeX
   /usr/local/lib/lhs2TeX
   /usr/share/lhs2TeX
   /usr/lib/lhs2TeX
)
Makefile:107: die Regel für Ziel „html“ scheiterte
make: *** [html] Fehler 1
```

**Comment by strake** [comment]
Try the latest; i recoded the files and incuded the missing ones, but i have no idea how to install hevea.sty, which it wants to use, so let me know how it works for you.

**Comment by nomeata** [comment]
Do you have `hevea` installed.

I had to change

```
        mv index.html $(file).html $(file).css $(file)[0-9]*.html $(file)[0-9]*.gif *motif.gif html
```

to

```
        mv index.html $(file).html $(file).css $(file)[0-9]*.html $(file)[0-9]*.png *motif.gif html
```

and add 

```
\usepackage[utf8]{inputenc}
```

to `Manual.lhs`, then I could build the manual.

**Comment by strake** [comment]
Hevea seems to not be on CTAN, so i built and installed it locally but have no idea how to tell TeX where to find it. How did you? Which TeX distro are you using?

**Comment by nomeata** [comment]
`apt-get install hevea` in my case.

**Comment by strake** [comment]
At last, works for me. I had to install Debian in qemu guest. Latest version (0.6.2.3) works for you also?

**Comment by nomeata** [comment]
> Latest version (0.6.2.3) works for you also?

✓
